#!/bin/bash
#Instalando GIT.
sudo apt install git -y

#Configurando usuario de GitHub.

echo 'Email en GitHub: '
read email
echo 'Usuario en GitHub: '
read usuario

git config --global user.email "$email"
git config --global user.name "$usuario"

#Clonando repositorios
mkdir -p /home/$USER/.baulera
cd
chmod 777 .baulera
cd .baulera
git clone https:/github.com/walterdiron/myshell.git