#!/bin/bash

#Actualizando repositorio.
cd
rm -r -f -d /home/$USER/.baulera/myshell
cd /home/$USER/.baulera
git clone https://github.com/walterdiron/myshell.git
cd
chmod 777 /home/$USER/.baulera/myshell/*

figlet Repositorio Actualizando