#!/bin/bash

#Actualizando repositorio TERMUXWALL.
cd
rm -r -f -d .baulera/myshell
cd .baulera
git clone https://github.com/walterdiron/myshell.git
cd
chmod +x .baulera/myshell/*

echo '. : R E P O S I T O R I O   A C T U A L I Z A D O : .'
cd
