#!/bin/bash

clear
cd

#Restaurar Bashrc
rm -r -f -d /data/data/com.termux/files/usr/etc/bash.bashrc
cp .baulera/myshell/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc

source /data/data/com.termux/files/usr/etc/bash.bashrc


Figlet Todo Listo
