#!/bin/bash

#Posicionar
cd
clear

#Instalar herramientas
pkg install zsh -y
pkg install wget -y
pkg install curl -y
pkg install cmatrix -y
pkg install hollywood -y
pkg install termux-api
pkg install man -y
pkg install figlet -y
pkg install zip -y
pkg install exa -y
termux-setup-storage

figlet Herramientas Instaladas
