#!/bin/bash

cd
apt install openssh -y
apt install net-tools -y
apt install procps -y
pkg install iproute2 -y

# Definir usuario y contraseña para la clave SSH
SSH_USER="walli"
IP_SERVIDOR=ip addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'

sshd -p 7547

clear
echo "Servidor SSH configurado y en ejecución."
echo
echo "Dirección IP $IP_SERVIDOR"

echo 'EJEMPLO -> ssh $IP_SERVIDOR -p 8022'

