#!/bin/bash

#Posicionar
cd
clear

#Instalar herramientas
apt install zsh -y
apt install neofetch -y
apt install wget -y
apt install curl -y
apt install cmatrix -y
apt install hollywood -y
apt install man -y
apt install manpages-es
dpkg-reconfigure locales
apt install figlet -y
apt install zip -y
apt install exa -y

figlet Herramientas Instaladas
