#!/bin/bash

#Actualizando repositorio TERMUXWALL.
cd
rm -r -f -d .baulera/myshell
cd .baulera
git clone https://github.com/walterdiron/myshell.git
cd
chmod +x .baulera/myshell/*

figlet Repositorio Actualizando